### ISSUE TITLE
Remove node_modules 

### ISSUE THREAD

**Issue by tsaxena4k** [Arshanshagarwal/To-do-List#1]
Node modules remove krde koi zaroorat nhi hai uski repo mein woh toh `create-react-app` ka part hi hai !

**Comment by Arshanshagarwal** [comment]
Han, vo galti se krdia tha, kyuki usme git.ignore file nhi bnai thi maine.
abhi vo complete bhini hai to do list. eksath krunga sab sahi

**Comment by tsaxena4k** [comment]
Sahi hai 🤘
